language: cpp
install:
  - sudo apt-get install libboost-test-dev -y
  - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/source.list
  - sudo apt-get update -qq

jobs:
  include:
    - stage: HW1
      script:
        - |
          if git diff --name-only HEAD^ | grep "HW1/"; then
            cd HW1 && \
            cmake . && \
            cmake --build . && \
            cmake --build . --target test && \
            cmake --build . --target package && \
            curl -T hw1-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -usub-mk:$BINARY_API_KEY "https://api.bintray.com/content/sub-mk/otus-cpp/hw1/$TRAVIS_BUILD_NUMBER/hw1-0.0.$TRAVIS_BUILD_NUMBER-Linix.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1" 1>&2;
          fi
